# Generated by Django 4.0.5 on 2022-07-06 15:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('current', models.BooleanField()),
                ('open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_username', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(blank=True, max_length=150)),
                ('pioneer', models.CharField(blank=True, max_length=150)),
                ('appointment', models.CharField(blank=True, max_length=150)),
                ('month', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('month_year_id', models.CharField(blank=True, max_length=150)),
                ('placements', models.CharField(blank=True, max_length=150)),
                ('video_showings', models.CharField(blank=True, max_length=150)),
                ('hours', models.CharField(blank=True, max_length=150)),
                ('return_visits', models.CharField(blank=True, max_length=150)),
                ('bible_studies', models.CharField(blank=True, max_length=150)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('DOB', models.CharField(blank=True, max_length=100)),
                ('parent_id', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('groupName', models.CharField(blank=True, max_length=150)),
                ('pioneer', models.CharField(blank=True, max_length=150)),
                ('appointment', models.CharField(blank=True, max_length=150)),
                ('privilege', models.CharField(blank=True, max_length=150)),
                ('pic', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=150)),
                ('created_at', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
