# Generated by Django 4.0.5 on 2022-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_report_publisherreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherreport',
            name='bible_studies',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='hours',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='placements',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='return_visits',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='video_showings',
            field=models.IntegerField(blank=True, max_length=150),
        ),
    ]
