# Generated by Django 4.0.5 on 2022-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_publisherreport_bible_studies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherreport',
            name='bible_studies',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='placements',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='return_visits',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='video_showings',
            field=models.IntegerField(blank=True),
        ),
    ]
