# Generated by Django 4.0.5 on 2022-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_publisherreport_bible_studies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
