# Generated by Django 4.0.5 on 2022-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_publisherprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publisherreport',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
