# Generated by Django 4.2.7 on 2023-12-25 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_publisherreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
