# Generated by Django 4.2.7 on 2023-12-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_publisherprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
